export interface KeywordTrigger {
  id: string;
  person: 1 | 2 | 3 | 4 | 5;
  scene: number;
  keyword: string;
  alternatives: string[];
  seekToFrame: number;
  animationLabel: string;
  scriptLine: string;
  autoPlayDuration: number;
  timeoutSeconds: number; // 0 = no auto-advance timeout
}

export const KEYWORD_MAP: KeywordTrigger[] = [
  // ── Escena 1 ─────────────────────────────────────────────────────────────
  {
    id: 's1_question',
    person: 1, scene: 1,
    keyword: 'ataque',
    alternatives: ['ocurre', 'detecta'],
    seekToFrame: 0,
    animationLabel: 'Pregunta aparece',
    scriptLine: 'Cuando ocurre un ataque y nadie lo detecta a tiempo, el daño ya está hecho.',
    autoPlayDuration: 60,
    timeoutSeconds: 12,
  },
  {
    id: 's1_stats',
    person: 1, scene: 1,
    keyword: 'industria',
    alternatives: ['promedio', '287'],
    seekToFrame: 80,
    animationLabel: 'Tarjetas de estadísticas',
    scriptLine: 'La industria tarda en promedio 287 días en detectar una brecha.',
    autoPlayDuration: 150,
    timeoutSeconds: 12,
  },
  {
    id: 's1_close',
    person: 1, scene: 1,
    keyword: 'milisegundos',
    alternatives: ['detectamos', 'TPs_data'],
    seekToFrame: 300,
    animationLabel: 'Línea final + equipo',
    scriptLine: 'Nosotros lo detectamos en milisegundos. Esto es TPs_data.',
    autoPlayDuration: 60,
    timeoutSeconds: 12,
  },

  // ── Escena 2 ─────────────────────────────────────────────────────────────
  {
    id: 's2_start',
    person: 1, scene: 2,
    keyword: 'arquitectura',
    alternatives: ['BTP', 'corre'],
    seekToFrame: 1200,
    animationLabel: 'SAP API aparece',
    scriptLine: 'Nuestra arquitectura corre completamente en SAP BTP.',
    autoPlayDuration: 80,
    timeoutSeconds: 12,
  },
  {
    id: 's2_flow',
    person: 1, scene: 2,
    keyword: 'pipeline',
    alternatives: ['FastAPI', 'asyncio'],
    seekToFrame: 1340,
    animationLabel: 'Pipeline + ML Model',
    scriptLine: 'Esos logs pasan por un pipeline de FastAPI con asyncio...',
    autoPlayDuration: 120,
    timeoutSeconds: 12,
  },
  {
    id: 's2_destinations',
    person: 1, scene: 2,
    keyword: 'destinos',
    alternatives: ['HANA', 'simultáneos'],
    seekToFrame: 1460,
    animationLabel: 'HANA + Webhook + Dashboard',
    scriptLine: '...el resultado va a tres destinos simultáneos: HANA, Webhook y dashboard.',
    autoPlayDuration: 120,
    timeoutSeconds: 12,
  },

  // ── Escena 3 ─────────────────────────────────────────────────────────────
  {
    id: 's3_observe',
    person: 1, scene: 3,
    keyword: 'OBSERVE',
    alternatives: ['primer paso', 'fetcher'],
    seekToFrame: 2400,
    animationLabel: 'Label OBSERVE + flujo',
    scriptLine: 'El primer paso del pipeline es OBSERVE.',
    autoPlayDuration: 90,
    timeoutSeconds: 12,
  },
  {
    id: 's3_parser',
    person: 1, scene: 3,
    keyword: 'normaliza',
    alternatives: ['parser', 'schema'],
    seekToFrame: 2530,
    animationLabel: 'log_parser.py aparece',
    scriptLine: '...normaliza los nombres de columnas y valida que el schema sea correcto.',
    autoPlayDuration: 80,
    timeoutSeconds: 12,
  },
  {
    id: 's3_table',
    person: 1, scene: 3,
    keyword: 'DataFrame',
    alternatives: ['output', 'pandas'],
    seekToFrame: 2600,
    animationLabel: 'Tabla de logs',
    scriptLine: 'El output es un DataFrame de pandas con columnas estandarizadas.',
    autoPlayDuration: 200,
    timeoutSeconds: 12,
  },
  {
    id: 's3_suspicious',
    person: 1, scene: 3,
    keyword: 'patrones',
    alternatives: ['IP', 'errores'],
    seekToFrame: 2850,
    animationLabel: 'Filas sospechosas se iluminan',
    scriptLine: 'Ya desde aquí podemos ver patrones: esta IP genera múltiples errores 403.',
    autoPlayDuration: 90,
    timeoutSeconds: 12,
  },

  // ── Escena 4 ─────────────────────────────────────────────────────────────
  {
    id: 's4_analyze',
    person: 1, scene: 4,
    keyword: 'ANALYZE',
    alternatives: ['features', 'métricas'],
    seekToFrame: 3600,
    animationLabel: 'Features aparecen',
    scriptLine: 'En la fase ANALYZE, features.py extrae 13 métricas de comportamiento.',
    autoPlayDuration: 200,
    timeoutSeconds: 12,
  },
  {
    id: 's4_model',
    person: 1, scene: 4,
    keyword: 'Isolation Forest',
    alternatives: ['modelo', 'supervisado'],
    seekToFrame: 3860,
    animationLabel: 'Label DETECT + score animado',
    scriptLine: 'Esas features entran al Isolation Forest — un modelo no supervisado.',
    autoPlayDuration: 120,
    timeoutSeconds: 12,
  },
  {
    id: 's4_alert',
    person: 1, scene: 4,
    keyword: 'umbral',
    alternatives: ['severidad', 'Alta'],
    seekToFrame: 4080,
    animationLabel: 'Alerta ALTA aparece',
    scriptLine: 'Nuestro umbral está en -0.50. El modelo la clasifica como severidad Alta.',
    autoPlayDuration: 120,
    timeoutSeconds: 12,
  },

  // ── Escena 5 ─────────────────────────────────────────────────────────────
  {
    id: 's5_btp',
    person: 1, scene: 5,
    keyword: 'Cloud Foundry',
    alternatives: ['BTP', 'corremos'],
    seekToFrame: 4800,
    animationLabel: 'Contenedor BTP aparece',
    scriptLine: 'Todo corre en SAP BTP Cloud Foundry.',
    autoPlayDuration: 160,
    timeoutSeconds: 12,
  },
  {
    id: 's5_connections',
    person: 1, scene: 5,
    keyword: 'connection pool',
    alternatives: ['HANA', 'latencia'],
    seekToFrame: 5060,
    animationLabel: 'Conexiones externas',
    scriptLine: '...nos conectamos a SAP HANA Cloud usando un connection pool.',
    autoPlayDuration: 160,
    timeoutSeconds: 12,
  },
  {
    id: 's5_live',
    person: 1, scene: 5,
    keyword: 'mayo',
    alternatives: ['corriendo', 'interrupciones'],
    seekToFrame: 5300,
    animationLabel: 'Badge Live en BTP',
    scriptLine: 'El sistema lleva corriendo en BTP desde el 4 de mayo sin interrupciones.',
    autoPlayDuration: 60,
    timeoutSeconds: 12,
  },

  // ── Escena 6 ─────────────────────────────────────────────────────────────
  {
    id: 's6_start',
    person: 1, scene: 6,
    keyword: 'flujo completo',
    alternatives: ['ataque real'],
    seekToFrame: 6000,
    animationLabel: 'Línea de tiempo aparece',
    scriptLine: 'Déjenme mostrarles el flujo completo de un ataque real.',
    autoPlayDuration: 80,
    timeoutSeconds: 12,
  },
  {
    id: 's6_ip',
    person: 1, scene: 6,
    keyword: '847',
    alternatives: ['requests', 'ciclo'],
    seekToFrame: 6080,
    animationLabel: 'Paso t+0ms',
    scriptLine: 'La IP 192.168.4.77 genera 847 requests en un solo ciclo.',
    autoPlayDuration: 80,
    timeoutSeconds: 12,
  },
  {
    id: 's6_score',
    person: 1, scene: 6,
    keyword: 'negativo',
    alternatives: ['score', '0.82'],
    seekToFrame: 6320,
    animationLabel: 'Paso t+180ms — score',
    scriptLine: 'El Isolation Forest devuelve un score negativo de -0.82.',
    autoPlayDuration: 80,
    timeoutSeconds: 12,
  },
  {
    id: 's6_response',
    person: 1, scene: 6,
    keyword: 'Incident Report',
    alternatives: ['Webhook', 'HANA'],
    seekToFrame: 6480,
    animationLabel: 'Pasos t+210ms–t+241ms',
    scriptLine: 'Se genera el Incident Report, se dispara el Webhook, y queda en HANA.',
    autoPlayDuration: 160,
    timeoutSeconds: 12,
  },
  {
    id: 's6_mttd',
    person: 1, scene: 6,
    keyword: 'MTTD',
    alternatives: ['245', 'total'],
    seekToFrame: 6750,
    animationLabel: 'MTTD 245ms aparece',
    scriptLine: 'MTTD total del pipeline: 245 milisegundos.',
    autoPlayDuration: 90,
    timeoutSeconds: 12,
  },

  // ── Escena 7 ─────────────────────────────────────────────────────────────
  {
    id: 's7_dashboard',
    person: 1, scene: 7,
    keyword: 'dashboard',
    alternatives: ['Streamlit', 'KPIs'],
    seekToFrame: 7200,
    animationLabel: 'Dashboard + KPIs aparecen',
    scriptLine: 'El dashboard de operaciones corre en Streamlit y se actualiza cada 5 segundos.',
    autoPlayDuration: 120,
    timeoutSeconds: 12,
  },
  {
    id: 's7_charts',
    person: 1, scene: 7,
    keyword: 'gráficas',
    alternatives: ['anomalías', 'evolución'],
    seekToFrame: 7400,
    animationLabel: 'Gráficas aparecen',
    scriptLine: '...dos gráficas en tiempo real: anomalías por hora y evolución del score.',
    autoPlayDuration: 100,
    timeoutSeconds: 12,
  },
  {
    id: 's7_feed',
    person: 1, scene: 7,
    keyword: 'feed',
    alternatives: ['analista', 'severidad'],
    seekToFrame: 7600,
    animationLabel: 'Log feed aparece',
    scriptLine: 'Y el feed de logs en vivo muestra cada IP flaggeada con su score y severidad.',
    autoPlayDuration: 60,
    timeoutSeconds: 12,
  },

  // ── Escena 8 ─────────────────────────────────────────────────────────────
  {
    id: 's8_mttd',
    person: 1, scene: 8,
    keyword: 'significa',
    alternatives: ['SAP', 'impacto'],
    seekToFrame: 8100,
    animationLabel: 'Tarjeta MTTD aparece',
    scriptLine: '¿Qué significa esto para SAP? Pasamos de 287 días a 245 milisegundos.',
    autoPlayDuration: 120,
    timeoutSeconds: 12,
  },
  {
    id: 's8_unsupervised',
    person: 1, scene: 8,
    keyword: 'etiquetados',
    alternatives: ['supervisado', 'aprende'],
    seekToFrame: 8300,
    animationLabel: 'Tarjeta no supervisado',
    scriptLine: '...el modelo no necesita ejemplos etiquetados.',
    autoPlayDuration: 100,
    timeoutSeconds: 12,
  },
  {
    id: 's8_native',
    person: 1, scene: 8,
    keyword: 'nativamente',
    alternatives: ['fricción', 'ecosistema'],
    seekToFrame: 8450,
    animationLabel: 'Tarjeta nativo BTP',
    scriptLine: 'Tercero, corre nativamente en BTP, sin fricción.',
    autoPlayDuration: 100,
    timeoutSeconds: 12,
  },
  {
    id: 's8_close',
    person: 1, scene: 8,
    keyword: 'respondiendo',
    alternatives: ['detectando', 'tiempo'],
    seekToFrame: 8700,
    animationLabel: 'Frase final aparece',
    scriptLine: 'Menos tiempo detectando. Más tiempo respondiendo.',
    autoPlayDuration: 90,
    timeoutSeconds: 12,
  },
];
