export interface KeywordTrigger {
  id: string;
  person: 1 | 2 | 3 | 4 | 5;
  scene: number;
  keyword: string;
  alternatives: string[];
  seekToFrame: number;
  animationLabel: string;
  scriptLine: string;
  autoPlayDuration: number;
  timeoutSeconds: number; // 0 = no auto-advance timeout
}

export const KEYWORD_MAP: KeywordTrigger[] = [
  // ── Scene 1 — Persona 3 ──────────────────────────────────────────────────
  {
    id: 's1_question',
    person: 3, scene: 1,
    keyword: 'ataque',
    alternatives: ['ocurre', 'detecta'],
    seekToFrame: 0,
    animationLabel: 'Pregunta aparece',
    scriptLine: '¿Qué pasa cuando un ataque ocurre en SAP...',
    autoPlayDuration: 60,
    timeoutSeconds: 12,
  },
  {
    id: 's1_stats',
    person: 3, scene: 1,
    keyword: 'industria',
    alternatives: ['promedio', '287'],
    seekToFrame: 80,
    animationLabel: 'Tarjetas de estadísticas',
    scriptLine: 'La industria tarda en promedio 287 días...',
    autoPlayDuration: 150,
    timeoutSeconds: 12,
  },
  {
    id: 's1_close',
    person: 3, scene: 1,
    keyword: 'milisegundos',
    alternatives: ['detectamos', 'TPs_data'],
    seekToFrame: 300,
    animationLabel: 'Línea final + equipo',
    scriptLine: 'Nosotros lo detectamos en milisegundos. Esto es TPs_data.',
    autoPlayDuration: 60,
    timeoutSeconds: 12,
  },

  // ── Scene 2 — Persona 3 ──────────────────────────────────────────────────
  {
    id: 's2_start',
    person: 3, scene: 2,
    keyword: 'arquitectura',
    alternatives: ['corre', 'BTP'],
    seekToFrame: 1200,
    animationLabel: 'SAP API aparece',
    scriptLine: 'Nuestra arquitectura corre completamente en SAP BTP.',
    autoPlayDuration: 80,
    timeoutSeconds: 12,
  },
  {
    id: 's2_flow',
    person: 3, scene: 2,
    keyword: 'pipeline',
    alternatives: ['FastAPI', 'asyncio'],
    seekToFrame: 1340,
    animationLabel: 'Pipeline + ML Model',
    scriptLine: 'Esos logs pasan por un pipeline de FastAPI con asyncio...',
    autoPlayDuration: 120,
    timeoutSeconds: 12,
  },
  {
    id: 's2_destinations',
    person: 3, scene: 2,
    keyword: 'destinos',
    alternatives: ['HANA', 'Webhook', 'simultáneos'],
    seekToFrame: 1460,
    animationLabel: 'HANA + Webhook + Dashboard',
    scriptLine: '...y el resultado va a tres destinos simultáneos...',
    autoPlayDuration: 120,
    timeoutSeconds: 12,
  },

  // ── Scene 3 — Persona 1 ──────────────────────────────────────────────────
  {
    id: 's3_observe',
    person: 1, scene: 3,
    keyword: 'OBSERVE',
    alternatives: ['primer paso', 'fetcher'],
    seekToFrame: 2400,
    animationLabel: 'Label OBSERVE + flujo',
    scriptLine: 'El primer paso del pipeline es OBSERVE.',
    autoPlayDuration: 90,
    timeoutSeconds: 12,
  },
  {
    id: 's3_parser',
    person: 1, scene: 3,
    keyword: 'normaliza',
    alternatives: ['parser', 'schema', 'columnas'],
    seekToFrame: 2530,
    animationLabel: 'log_parser.py aparece',
    scriptLine: '...que normaliza los nombres de columnas y valida el schema.',
    autoPlayDuration: 80,
    timeoutSeconds: 12,
  },
  {
    id: 's3_table',
    person: 1, scene: 3,
    keyword: 'DataFrame',
    alternatives: ['output', 'pandas'],
    seekToFrame: 2600,
    animationLabel: 'Tabla de logs',
    scriptLine: 'El output es un DataFrame de pandas...',
    autoPlayDuration: 200,
    timeoutSeconds: 12,
  },
  {
    id: 's3_suspicious',
    person: 1, scene: 3,
    keyword: 'patrones',
    alternatives: ['IP', 'errores', 'sospechosa'],
    seekToFrame: 2850,
    animationLabel: 'Filas sospechosas se iluminan',
    scriptLine: 'Ya desde aquí podemos ver patrones...',
    autoPlayDuration: 90,
    timeoutSeconds: 12,
  },

  // ── Scene 4 — Persona 1 ──────────────────────────────────────────────────
  {
    id: 's4_analyze',
    person: 1, scene: 4,
    keyword: 'ANALYZE',
    alternatives: ['features', 'métricas'],
    seekToFrame: 3600,
    animationLabel: 'Features aparecen',
    scriptLine: 'En la fase ANALYZE, el módulo features.py...',
    autoPlayDuration: 200,
    timeoutSeconds: 12,
  },
  {
    id: 's4_model',
    person: 1, scene: 4,
    keyword: 'Isolation Forest',
    alternatives: ['modelo', 'no supervisado'],
    seekToFrame: 3860,
    animationLabel: 'Label DETECT + score animado',
    scriptLine: 'Esas features entran al Isolation Forest...',
    autoPlayDuration: 120,
    timeoutSeconds: 12,
  },
  {
    id: 's4_alert',
    person: 1, scene: 4,
    keyword: 'umbral',
    alternatives: ['severidad', 'Alta', 'clasifica'],
    seekToFrame: 4080,
    animationLabel: 'Alerta ALTA aparece',
    scriptLine: 'El modelo la clasifica automáticamente como severidad Alta.',
    autoPlayDuration: 120,
    timeoutSeconds: 12,
  },

  // ── Scene 5 — Persona 2 ──────────────────────────────────────────────────
  {
    id: 's5_btp',
    person: 2, scene: 5,
    keyword: 'Cloud Foundry',
    alternatives: ['BTP', 'corremos'],
    seekToFrame: 4800,
    animationLabel: 'Contenedor BTP aparece',
    scriptLine: 'Todo corre en SAP BTP Cloud Foundry.',
    autoPlayDuration: 160,
    timeoutSeconds: 12,
  },
  {
    id: 's5_connections',
    person: 2, scene: 5,
    keyword: 'connection pool',
    alternatives: ['HANA', 'conectamos', 'latencia'],
    seekToFrame: 5060,
    animationLabel: 'Conexiones externas',
    scriptLine: 'Hacia afuera nos conectamos a SAP HANA Cloud...',
    autoPlayDuration: 160,
    timeoutSeconds: 12,
  },
  {
    id: 's5_live',
    person: 2, scene: 5,
    keyword: 'mayo',
    alternatives: ['corriendo', 'BTP desde'],
    seekToFrame: 5300,
    animationLabel: 'Badge Live en BTP',
    scriptLine: 'El sistema lleva corriendo en BTP desde el 4 de mayo.',
    autoPlayDuration: 60,
    timeoutSeconds: 12,
  },

  // ── Scene 6 — Persona 5 ──────────────────────────────────────────────────
  {
    id: 's6_start',
    person: 5, scene: 6,
    keyword: 'flujo completo',
    alternatives: ['ataque real', 'muéstrenles'],
    seekToFrame: 6000,
    animationLabel: 'Línea de tiempo aparece',
    scriptLine: 'Déjenme mostrarles el flujo completo de un ataque real.',
    autoPlayDuration: 80,
    timeoutSeconds: 12,
  },
  {
    id: 's6_ip',
    person: 5, scene: 6,
    keyword: '847',
    alternatives: ['requests', '192.168'],
    seekToFrame: 6080,
    animationLabel: 'Paso t+0ms',
    scriptLine: 'La IP 192.168.4.77 genera 847 requests en un solo ciclo.',
    autoPlayDuration: 80,
    timeoutSeconds: 12,
  },
  {
    id: 's6_features',
    person: 5, scene: 6,
    keyword: 'error rate',
    alternatives: ['brute force', 'extractor'],
    seekToFrame: 6240,
    animationLabel: 'Pasos t+45ms y t+112ms',
    scriptLine: 'El extractor de features detecta error_rate de 0.73...',
    autoPlayDuration: 80,
    timeoutSeconds: 12,
  },
  {
    id: 's6_score',
    person: 5, scene: 6,
    keyword: 'negativo',
    alternatives: ['score', '-0.82'],
    seekToFrame: 6320,
    animationLabel: 'Paso t+180ms — score',
    scriptLine: 'El Isolation Forest devuelve un score de -0.82.',
    autoPlayDuration: 80,
    timeoutSeconds: 12,
  },
  {
    id: 's6_response',
    person: 5, scene: 6,
    keyword: 'Incident Report',
    alternatives: ['Webhook', 'persistido', 'HANA'],
    seekToFrame: 6480,
    animationLabel: 'Pasos t+210ms–t+241ms',
    scriptLine: 'Se genera el Incident Report, se dispara el Webhook...',
    autoPlayDuration: 160,
    timeoutSeconds: 12,
  },
  {
    id: 's6_mttd',
    person: 5, scene: 6,
    keyword: 'MTTD',
    alternatives: ['total', '245'],
    seekToFrame: 6750,
    animationLabel: 'MTTD 245ms aparece',
    scriptLine: 'MTTD total del pipeline: 245 milisegundos.',
    autoPlayDuration: 90,
    timeoutSeconds: 12,
  },

  // ── Scene 7 — Persona 4 ──────────────────────────────────────────────────
  {
    id: 's7_dashboard',
    person: 4, scene: 7,
    keyword: 'dashboard',
    alternatives: ['Streamlit', 'KPIs'],
    seekToFrame: 7200,
    animationLabel: 'Dashboard + KPIs aparecen',
    scriptLine: 'El dashboard de operaciones corre en Streamlit...',
    autoPlayDuration: 120,
    timeoutSeconds: 12,
  },
  {
    id: 's7_charts',
    person: 4, scene: 7,
    keyword: 'gráficas',
    alternatives: ['anomalías por hora', 'evolución'],
    seekToFrame: 7400,
    animationLabel: 'Gráficas aparecen',
    scriptLine: 'Abajo tenemos dos gráficas en tiempo real...',
    autoPlayDuration: 100,
    timeoutSeconds: 12,
  },
  {
    id: 's7_feed',
    person: 4, scene: 7,
    keyword: 'feed',
    alternatives: ['analista', 'pantalla'],
    seekToFrame: 7600,
    animationLabel: 'Log feed aparece',
    scriptLine: 'Y el feed de logs en vivo muestra cada IP flaggeada...',
    autoPlayDuration: 60,
    timeoutSeconds: 12,
  },

  // ── Scene 8 — Persona 3 ──────────────────────────────────────────────────
  {
    id: 's8_mttd',
    person: 3, scene: 8,
    keyword: 'significa',
    alternatives: ['SAP', 'impacto'],
    seekToFrame: 8100,
    animationLabel: 'Tarjeta MTTD aparece',
    scriptLine: '¿Qué significa esto para SAP?',
    autoPlayDuration: 120,
    timeoutSeconds: 12,
  },
  {
    id: 's8_unsupervised',
    person: 3, scene: 8,
    keyword: 'etiquetados',
    alternatives: ['supervisado', 'aprende'],
    seekToFrame: 8300,
    animationLabel: 'Tarjeta no supervisado',
    scriptLine: 'Usamos aprendizaje no supervisado...',
    autoPlayDuration: 100,
    timeoutSeconds: 12,
  },
  {
    id: 's8_native',
    person: 3, scene: 8,
    keyword: 'nativamente',
    alternatives: ['fricción', 'ecosistema'],
    seekToFrame: 8450,
    animationLabel: 'Tarjeta nativo BTP',
    scriptLine: 'Tercero, corre nativamente en BTP.',
    autoPlayDuration: 100,
    timeoutSeconds: 12,
  },
  {
    id: 's8_close',
    person: 3, scene: 8,
    keyword: 'respondiendo',
    alternatives: ['detectando', 'menos tiempo'],
    seekToFrame: 8700,
    animationLabel: 'Frase final aparece',
    scriptLine: 'Menos tiempo detectando. Más tiempo respondiendo.',
    autoPlayDuration: 90,
    timeoutSeconds: 12,
  },
];
